name = "Aeronautics++"
author = "siscodemc"
version = "1.1.0-BETA-2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2379376bba01e5b6f8be6640afcf107f6a2f626e9be70640fb6aa0cc60666dd8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
