name = "Aeronautics++"
author = "siscodemc"
version = "1.1.0-BETA-2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e22a51cea7eb9f57c7943c7717387a377f833790d9eec9baeb5bf9c0d7f5ef5a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
